### ISSUE TITLE
Page didn't load after 30 seconds, trying again!

### ISSUE THREAD

**Issue by Little-Chen-T** [remcalu/Poocoin-Monitor#1]
The element on the web page is always missing, So I've been loading web pages.

"Page didn't load after 30 seconds, trying again!"
"Page didn't load after 30 seconds, trying again!"
"Page didn't load after 30 seconds, trying again!"
"Page didn't load after 30 seconds, trying again!"

。。。

how can I solve this problem

**Comment by Little-Chen-T** [comment]
By opening Google browser, I can manually locate the elements we want
![image](https://user-images.githubusercontent.com/82454540/143270901-f9fd5cb9-717d-498c-afa4-94a44d20e4a5.png)

**Comment by Little-Chen-T** [comment]
I checked. The browser has no restricted access, but why can't we find the element we want. I hope someone can help me. Thank you very much

![image](https://user-images.githubusercontent.com/82454540/143271225-b3e84168-49d0-498d-81eb-9382c51a7095.png)

**Comment by remcalu** [comment]
Hey, sorry I didn't see your issue until now, I haven't updated this repository in several months so everything is outdated as poocoin changes their website quite frequently, however you can use my code as a starting point by forking and build off of it, you could also open up a PR if it's a quick fix 🙂

**Comment by Little-Chen-T** [comment]
Thank you! Your code is very well written and still applicable to poocoin. I solved the problem by commenting out this statement "coptions.add_argument('--headless')", and allowing the browser to load it, but I can't let chrome run monitoring data in the background.

**Comment by remcalu** [comment]
No problem, yeah I think I was having that issue with another one of my webscrapers, anyway, glad it works now!
